### ISSUE TITLE
[Unity Export and Run] Caused by: java.lang.IllegalArgumentException: Unable to find native library: main

### ISSUE THREAD

**Issue by rosarioconti** [onepf/OpenIAB#142]
1) I have installed the package from the unity store
2) Exported and run the project from unity 4.1.2.f1 for Android
3) I get this error:
Caused by: java.lang.IllegalArgumentException: Unable to find native library: main

Looks to me that a library is missing.here but not sure which lib.

Anyone can help?
thanks

The entire error log;

02-24 00:40:42.835: E/AndroidRuntime(19058): FATAL EXCEPTION: main
02-24 00:40:42.835: E/AndroidRuntime(19058): java.lang.Error: FATAL EXCEPTION [main]
02-24 00:40:42.835: E/AndroidRuntime(19058): Unity version     : 4.1.2f1
02-24 00:40:42.835: E/AndroidRuntime(19058): Device model      : samsung  
02-24 00:40:42.835: E/AndroidRuntime(19058): Device fingerprint: xxxxxxxxxxxxx:user/release-keys
02-24 00:40:42.835: E/AndroidRuntime(19058): Caused by: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxx.xxx com.unity3d.player.UnityPlayerNativeActivity}: java.lang.IllegalArgumentException: Unable to find native library: main
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2110)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2135)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.ActivityThread.access$700(ActivityThread.java:143)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1241)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.os.Handler.dispatchMessage(Handler.java:99)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.os.Looper.loop(Looper.java:137)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.ActivityThread.main(ActivityThread.java:4950)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at java.lang.reflect.Method.invokeNative(Native Method)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at java.lang.reflect.Method.invoke(Method.java:511)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1004)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:771)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at dalvik.system.NativeStart.main(Native Method)
02-24 00:40:42.835: E/AndroidRuntime(19058): Caused by: java.lang.IllegalArgumentException: Unable to find native library: main
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.NativeActivity.onCreate(NativeActivity.java:187)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at com.unity3d.player.UnityPlayerNativeActivity.onCreate(Unknown Source)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.Activity.performCreate(Activity.java:5179)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
02-24 00:40:42.835: E/AndroidRuntime(19058):    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2074)

**Comment by Leekifu** [comment]
is lua library    not   found       but my project exist this library
