### ISSUE TITLE
This version of the application is not configured for billing through Google Play

### ISSUE THREAD

**Issue by rubdottocom** [onepf/OpenIAB#177]
Hi, I'm not sure and maybe it is my own error, but I can't find what is wrong.
It seems that since I use OpenIAB, all purchases for new in app products results in:

"This version of the application is not configured for billing through Google Play. Check the help center for more information".

I'm testing with new "test" real managed items (items that only can be purchased once).

My google/gmail account is set as testing, I'm trying with a signed APK that uses the same key store than before using OpenIAB. This is my proguard rules:

```
# AMAZON
-dontwarn com.amazon.**
-keep class com.amazon.** {*;}
-keepattributes *Annotation*
-dontoptimize

# GOOGLE
-keep class com.android.vending.billing.**
```

Do you know what could be going wrong? Can I check anything more or try to do another type of test?

Thank you very much, btw purchases on Amazon that was the reason that I'm using thing works like a charm.

**Comment by naveedahmad99** [comment]
Oh man, Thanks alot

**Comment by naveedahmad99** [comment]
Signed apk and activated managed product (inapp purchases) solved my problem. I was wondering why my inapp purchases not working. :)

**Comment by aminorex** [comment]
The Google platform is broken.
