### ISSUE TITLE
Fortumo appears to be broken

### ISSUE THREAD

**Issue by codingcaveman** [onepf/OpenIAB#188]
I've not been able to use Fortumo in OpenIAB, either in my own app or in your TrivialDrive example.  Upon setting up OpenIAB, I get this error in the log:

FortumoStore(19678): isBillingAvailable: has FEATURE_TELEPHONY true
FortumoStore(19678): billing is not supported due to Can't obtain fortumoPrice details from  the server. (response: 0:OK)

The above is reproducible by adding supportFortumo= true to the setup options in TrivialDrive.  I can work around this by downloading the inapp details xml file directly from Fortumo (as they describe for bundling in-apps for offline use).  If I do this, OpenIAB setup completes successfully, however I cannot purchase an item.  I get an error toast explaining "Only widget payments are supported for this carrier"

However, the Fortumo demo app available from m.fortumo.com works fine, so I suspect it is an OpenIAB integration issue.

**Comment by linvuz01** [comment]
Hi everyone,

I'm having a problem creating a service, well not necessary creating it. I don't understand one of the info I need to fill out, where it ask "to which url your payment request forwaded to". Can anyone help in explaining what is really needed here...
