### ISSUE TITLE
Inconsistent result codes in onIabPurchaseFinished

### ISSUE THREAD

**Issue by Tolriq** [onepf/OpenIAB#231]
Hi,

Return values in onIabPurchaseFinished is quite inconsistent between stores and make it hard to know what to handle how.

Half stores will answers with IabHelper.BILLING_RESPONSE_RESULT type codes.
And other half will answer with IabHelper.IABHELPER_ type codes.

All store should answer with the same code for the same result. (Typically the user cancelled event)

Regards,
Tolriq

**Comment by akarimova** [comment]
for the next version of the library
