### ISSUE TITLE
Update HOWTO for Appstores -  permission.BILLING

### ISSUE THREAD

**Issue by oorlov** [onepf/OpenIAB#237]
org.onepf.openiab.permission.BILLING needs to be mention in spec. 
- why is it needed
- how to implement for system-level Appstore.apk
- how to implement for downloadable Appstore.apk

**Comment by sp-miguel-janer** [comment]
why is it needed??

**Comment by oorlov** [comment]
OpenIAB compatible Appstores are supposed to check application has such permission and prevent purchases if it is not there.
If permission is in Manifest, user will see it when install the app, so there will be no surprise if app requests to pay.
