### ISSUE TITLE
SlideME Store, Billing unavailable

### ISSUE THREAD

**Issue by xlREDlx** [onepf/OpenIAB#242]
Hi, I have been trying to add IAP to my game in SlideME store, but for some reason it can never connect to the store. I already implemented IAP for Google Play and it works without any problem, and it seems like it discovers the SlideME store, so I don't know what might be wrong. The unitypackage that I'm using is this one: https://yadi.sk/d/yc-WEwhsU4T9J
The logs after trying to do init to times are the following:

06-19 22:05:14.691  27568-27568/com.GameSin.ZombieAttack D/OpenIAB-UnityPlugin﹕ createBroadcasts
06-19 22:05:14.691  27568-27568/com.GameSin.ZombieAttack D/OpenIAB-UnityPlugin﹕ Starting setup.
06-19 22:05:19.992  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 5232 startSetup() discovered openstores: []
06-19 22:05:20.636  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 5889 0 inventory candidates
06-19 22:05:20.640  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 5891 inventory check done
06-19 22:05:20.640  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 5892 select equipped
06-19 22:05:20.765  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 6016 select non-equipped
06-19 22:05:20.765  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 6017 fireSetupFinished() === SETUP DONE === result: IabResult: 3, Billing isn't supported (response: 3:Billing Unavailable)
06-19 22:05:20.765  27568-27568/com.GameSin.ZombieAttack D/OpenIAB-UnityPlugin﹕ Setup finished.
06-19 22:05:20.765  27568-27568/com.GameSin.ZombieAttack E/OpenIAB-UnityPlugin﹕ Problem setting up in-app billing: IabResult: 3, Billing isn't supported (response: 3:Billing Unavailable)
06-19 22:05:20.804  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 6055 startSetup() disposing com.amazon.apps
06-19 22:05:20.804  27568-28218/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 6056 startSetup() disposing com.nokia.nstore
06-19 22:05:22.136  27568-27568/com.GameSin.ZombieAttack D/OPENIAB﹕ discoverOpenStores() appstoresService connected for component: com.slideme.sam.manager/.inapp.openiab.OpenIabStoreService
06-19 22:05:22.492  27568-27568/com.GameSin.ZombieAttack D/OPENIAB﹕ discoverOpenStores() add new OpenStore: OpenStore {name: SlideME, component: ComponentInfo{com.slideme.sam.manager/com.slideme.sam.manager.inapp.openiab.OpenIabStoreService}}
06-19 22:06:38.414  27568-27568/com.GameSin.ZombieAttack D/OpenIAB-UnityPlugin﹕ createBroadcasts
06-19 22:06:38.414  27568-27568/com.GameSin.ZombieAttack D/OpenIAB-UnityPlugin﹕ Starting setup.
06-19 22:06:38.437  27568-27568/com.GameSin.ZombieAttack D/OPENIAB﹕ discoverOpenStores() appstoresService connected for component: com.slideme.sam.manager/.inapp.openiab.OpenIabStoreService
06-19 22:06:38.453  27568-27568/com.GameSin.ZombieAttack D/OPENIAB﹕ discoverOpenStores() add new OpenStore: OpenStore {name: SlideME, component: ComponentInfo{com.slideme.sam.manager/com.slideme.sam.manager.inapp.openiab.OpenIabStoreService}}
06-19 22:06:38.453  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 41 startSetup() discovered openstores: [OpenStore {name: SlideME, component: ComponentInfo{com.slideme.sam.manager/com.slideme.sam.manager.inapp.openiab.OpenIabStoreService}}]
06-19 22:06:38.667  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 256 0 inventory candidates
06-19 22:06:38.667  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 256 inventory check done
06-19 22:06:38.667  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 256 select equipped
06-19 22:06:38.886  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 472 select non-equipped
06-19 22:06:38.886  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 472 fireSetupFinished() === SETUP DONE === result: IabResult: 3, Billing isn't supported (response: 3:Billing Unavailable)
06-19 22:06:38.886  27568-27568/com.GameSin.ZombieAttack D/OpenIAB-UnityPlugin﹕ Setup finished.
06-19 22:06:38.886  27568-27568/com.GameSin.ZombieAttack E/OpenIAB-UnityPlugin﹕ Problem setting up in-app billing: IabResult: 3, Billing isn't supported (response: 3:Billing Unavailable)
06-19 22:06:38.894  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 482 startSetup() disposing SlideME
06-19 22:06:38.929  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 518 startSetup() disposing com.amazon.apps
06-19 22:06:38.941  27568-28798/com.GameSin.ZombieAttack D/OPENIAB﹕ in: 527 startSetup() disposing com.nokia.nstore

**Comment by akarimova** [comment]
cannot reproduce on the latest releases
