### ISSUE TITLE
FATAL EXCEPTION: inv-check[SlideME] when testing with SlideME App Store

### ISSUE THREAD

**Issue by ArmixMex** [onepf/OpenIAB#266]
My App works with Google and Amazon but when testing with SlideME I have got a NullPointerException.

Any idea?????

07-21 19:14:40.027: D/MyOpenIAB(13437): Starting setup.
07-21 19:14:40.076: D/OpenIabHelper(13437): discoverOpenStores() appstoresService connected for component: com.slideme.sam.manager/.inapp.openiab.OpenIabStoreService
07-21 19:14:40.080: D/IabHelper(13437): IAB helper created.
07-21 19:14:40.081: D/OpenIabHelper(13437): discoverOpenStores() add new OpenStore: OpenStore {name: SlideME, component: ComponentInfo{com.slideme.sam.manager/com.slideme.sam.manager.inapp.openiab.OpenIabStoreService}}
07-21 19:14:40.083: D/OpenIabHelper(13437): in: 54 startSetup() discovered openstores: [OpenStore {name: SlideME, component: ComponentInfo{com.slideme.sam.manager/com.slideme.sam.manager.inapp.openiab.OpenIabStoreService}}]
07-21 19:14:40.086: D/AmazonAppstore(13437): hasAmazonClasses() cannot load class com.amazon.android.Kiwi 
07-21 19:14:40.087: D/AmazonAppstore(13437): isPackageInstaller() sandBox: true
07-21 19:14:40.327: D/OpenIabHelper(13437): in: 298 1 inventory candidates
07-21 19:14:40.328: D/IabHelper(13437): Starting in-app billing setup.

07-21 19:14:40.366: D/IabHelper(13437): Billing service connected.
07-21 19:14:40.366: D/IabHelper(13437): Checking for in-app billing 3 support.
07-21 19:14:40.369: D/IabHelper(13437): In-app billing version 3 supported for com.armix.karylux
07-21 19:14:40.372: D/IabHelper(13437): Subscriptions AVAILABLE.
07-21 19:14:40.381: D/OpenIabHelper(13437): in: 352 billing set SlideME
07-21 19:14:40.390: D/IabHelper(13437): Querying owned items, item type: inapp
07-21 19:14:40.390: D/IabHelper(13437): Package name: com.armix.karylux
07-21 19:14:40.392: D/IabHelper(13437): Calling getPurchases with continuation token: null

07-21 19:14:42.383: W/dalvikvm(13437): threadid=16: thread exiting with uncaught exception (group=0x40a75228)

07-21 19:14:42.401: E/AndroidRuntime(13437): FATAL EXCEPTION: inv-check[SlideME]
07-21 19:14:42.401: E/AndroidRuntime(13437): java.lang.NullPointerException
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at android.os.Parcel.readException(Parcel.java:1333)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at android.os.Parcel.readException(Parcel.java:1281)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at org.onepf.oms.IOpenInAppBillingService$Stub$Proxy.getPurchases(IOpenInAppBillingService.java:280)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at org.onepf.oms.appstore.OpenAppstore$IOpenInAppBillingWrapper.getPurchases(OpenAppstore.java:193)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at org.onepf.oms.appstore.googleUtils.IabHelper.queryPurchases(IabHelper.java:887)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at org.onepf.oms.appstore.googleUtils.IabHelper.queryInventory(IabHelper.java:569)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at org.onepf.oms.OpenIabHelper$4$1.run(OpenIabHelper.java:773)
07-21 19:14:42.401: E/AndroidRuntime(13437): 	at java.lang.Thread.run(Thread.java:861)

07-21 19:14:44.514: D/OpenIabHelper(13437): Disposing.
07-21 19:14:50.381: D/OpenIabHelper(13437): in: 10352 inventory check done
07-21 19:14:50.381: D/OpenIabHelper(13437): in: 10353 select equipped
07-21 19:14:50.385: D/OpenIabHelper(13437): in: 10357 select non-equipped
07-21 19:14:50.385: D/OpenIabHelper(13437): Successfully initialized with non-equipped store: SlideME
07-21 19:14:50.387: D/OpenIabHelper(13437): in: 10359 startSetup() disposing com.amazon.apps
07-21 19:14:50.388: D/OpenIabHelper(13437): in: 10360 startSetup() disposing com.tmobile.store
07-21 19:14:50.392: D/OpenIabHelper(13437): in: 10362 startSetup() disposing com.nokia.nstore

**Comment by akarimova** [comment]
closed as outdated
