### ISSUE TITLE
not working on Nexus 7

### ISSUE THREAD

**Issue by Pyxxym** [onepf/OpenIAB#291]
Hi,

I'm trying to make IAP with UNITY on Android (and iOS next...) but OpenIAB crashed with exporting locally and when I upload the APK to Google Play Developer Console, it says "This app is incompatible with your device."
It's the same thing when I use the Angry Bots demo.

I tried ALL following combinaisons which failed
(Unity 4.52 / 4.3.1) +  (jdk 6 x86 / x64 / jdk 7 x86 / x64)
## There s the log in debug version

C:\Program Files (x86)\Android\android-sdk\platform-tools>adb logcat -s Unity
- daemon not running. starting it now on port 5037 *
- daemon started successfully *
- waiting for device -
  --------- beginning of /dev/log/system
  --------- beginning of /dev/log/main
  I/Unity   (21773): gles_mode = 0 (integer)
  I/Unity   (21773): splash_mode = 0 (integer)
  I/Unity   (21773): hide_status_bar = False (bool)
  I/Unity   (21773): useObb = False (bool)
  I/Unity   (21773): development_player = True (bool)
  D/Unity   (21773): surfaces: attach glview
  I/Unity   (21773): onResume
  D/Unity   (21773): [EGL] Attaching window 0x763ef888
  I/Unity   (21773): windowFocusChanged: true
  D/Unity   (21773): SystemInfo CPU = ARMv7 VFPv3 NEON, Cores = 4, Memory = 1805mb
  D/Unity   (21773): [SHA1] 5a6d379f25e76e2f66d7c02f2a4547b73dec6d2f   15831785 bytes ~ lib/armeabi-v7a/libunity.so
  D/Unity   (21773): Mono path[0] = '/data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed'
  D/Unity   (21773): Mono config path = 'assets/bin/Data/Managed'
  D/Unity   (21773): PlayerConnection initialized from /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data (debug = 0)
  D/Unity   (21773): PlayerConnection initialized network socket : 0.0.0.0 55356
  D/Unity   (21773): PlayerConnection initialized unix socket : Unity-com.pyxxym.openiab
  D/Unity   (21773): Multi-casting "[IP] 10.57.103.89 [Port] 55356 [Flags] 3 [Guid] 719379853 [EditorId] 1517440076 [Version] 1048832 [Id] AndroidPlayer(asus_Nexu
  s_7@10.57.103.89) [Debug] 1" to [225.0.0.222:54997]...
  D/Unity   (21773): Waiting for connection from host on [10.57.103.89:55356]...
  D/Unity   (21773): Timed out. Continuing without host connection.
  D/Unity   (21773): Using monoOptions --debugger-agent=transport=dt_socket,embedding=1,defer=y,address=0.0.0.0:56853
  D/Unity   (21773): InitializeMonoFromMain OK (770f4ee0)
  D/Unity   (21773): PlayerConnection already initialized - listening to [10.57.103.89:55356]
  D/Unity   (21773): PlayerInitEngineNoGraphics OK
  D/Unity   (21773): [EGL] Request: ES2 RGB16 565 16NLZ/8
  D/Unity   (21773): [EGL] Selected: ES2 RGB16 565 24/8
  D/Unity   (21773): Renderer: Adreno (TM) 320
  D/Unity   (21773): Vendor:   Qualcomm
  D/Unity   (21773): Version:  OpenGL ES 3.0 V@53.0 AU@  (CL@)
  D/Unity   (21773): GL_AMD_compressed_ATC_texture GL_AMD_performance_monitor GL_AMD_program_binary_Z400 GL_EXT_debug_label GL_EXT_debug_marker GL_EXT_discard_fra
  mebuffer GL_EXT_robustness GL_EXT_texture_format_BGRA8888 GL_EXT_texture_type_2_10_10_10_REV GL_NV_fence GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth_textur
  e GL_OES_depth24 GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_fragment_precision_high GL_OES_get_program
  _binary GL_OES_packed_depth_stencil GL_OES_depth_texture_cube_map GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_texture_3D GL_OES_texture_float GL_OES_te
  xture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_OES_vertex_type_10_10_10_2 GL_OES_vertex_array_object GL_QCOM_
  alpha_test GL_QCOM_binning_control GL_QCOM_driver_control GL_QCOM_perfmon_global_mode GL_QCOM_extended_get GL_QCOM_extended_get2 GL_QCOM_tiled_rendering GL_QCOM
  _writeonly_rendering GL_EXT_sRGB GL_EXT_texture_filter_anisotropic GL_EXT_color_bu
  D/Unity   (21773): ffer_float GL_EXT_color_buffer_half_float GL_EXT_disjoint_timer_query
  D/Unity   (21773): Creating OpenGLES2.0 graphics device
  D/Unity   (21773): InitializeGfxDevice OK
  D/Unity   (21773): Initialize engine version: 4.5.2f1 (9abb1b59b47c)
  D/Unity   (21773): Begin MonoManager ReloadAssembly
  D/Unity   (21773): Platform assembly: /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/UnityEngine.dll (this message is harmless)
  D/Unity   (21773): Loading /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/UnityEngine.dll into Unity Child Domain
  D/Unity   (21773): Platform assembly: /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/Assembly-CSharp-firstpass.dll (this message is harmless)
  D/Unity   (21773): Loading /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/Assembly-CSharp-firstpass.dll into Unity Child Domain
  D/Unity   (21773): Platform assembly: /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/Assembly-CSharp.dll (this message is harmless)
  D/Unity   (21773): Loading /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/Assembly-CSharp.dll into Unity Child Domain
  D/Unity   (21773): Platform assembly: /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/OpenIAB_W8Plugin.dll (this message is harmless)
  D/Unity   (21773): Loading /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/OpenIAB_W8Plugin.dll into Unity Child Domain
  D/Unity   (21773): - Completed reload, in  0.129 seconds
  D/Unity   (21773): PlayerInitEngineGraphics OK
  D/Unity   (21773): Found 12 native sensors
  D/Unity   (21773): Sensor :        Accelerometer ( 1) ; 0.001190 / 0.00s ; MPL Accelerometer / InvenSense
  D/Unity   (21773): Sensor :        Accelerometer ( 1) ; 0.001190 / 0.00s ; MPL Accelerometer / InvenSense
  D/Unity   (21773): Platform assembly: /data/app/com.pyxxym.openiab-1.apk/assets/bin/Data/Managed/System.Core.dll (this message is harmless)
  D/Unity   (21773): Sensor :        Accelerometer ( 1) ; 0.001190 / 0.00s ; MPL Accelerometer / InvenSense
  I/Unity   (21773): *********\* Android OpenIAB plugin initialized **********
  I/Unity   (21773): UnityEngine.Debug:Internal_Log(Int32, String, Object)
  I/Unity   (21773): UnityEngine.Debug:Log(Object)
  I/Unity   (21773): OnePF.OpenIAB:.cctor() (at D:\documents_PERSO\=VIDEO_GAME\OpenIAB-Unity\Assets\Plugins\OpenIAB\OpenIAB.cs:41)
  I/Unity   (21773): OpenIABTest:Start() (at D:\documents_PERSO\=VIDEO_GAME\OpenIAB-Unity\Assets\OpenIAB-demo\OpenIABTest.cs:76)
  I/Unity   (21773): OpenIABTest:Start() (at D:\documents_PERSO\=VIDEO_GAME\OpenIAB-Unity\Assets\OpenIAB-demo\OpenIABTest.cs:67)
  I/Unity   (21773):
  I/Unity   (21773): (Filename: D Line: 0)
  -------------------------------------------------------
  My App:
  https://play.google.com/store/apps/details?id=com.pyxxym.openiab

If someone can help, it ll be nice :)
Thanks

**Comment by HeavyD** [comment]
Which line?
