### ISSUE TITLE
NPE, Samsung Query inventory

### ISSUE THREAD

**Issue by perpetuummedia** [onepf/OpenIAB#307]
Hi all,

first of all I hope everyone is doing well. This is my 1st post here.

We are using the IAB lib and find it a great idea. There is one issue we found however that can be reproduced..

Once the check inventory has been started, bring the app to background via home key.... What happens then just before the onActivityResult would be triggered (I guess) is below:

Process: com.bla.ads, PID: 14350
E/AndroidRuntime(14350): java.lang.NullPointerException
E/AndroidRuntime(14350): 	at org.onepf.oms.appstore.SamsungAppsBillingService.queryInventory(SamsungAppsBillingService.java:188)
E/AndroidRuntime(14350): 	at org.onepf.oms.OpenIabHelper.queryInventory(OpenIabHelper.java:973)
E/AndroidRuntime(14350): 	at org.onepf.oms.OpenIabHelper$5.run(OpenIabHelper.java:999)
E/AndroidRuntime(14350): 	at java.lang.Thread.run(Thread.java:841)

The originating activity (from where we initiate the query is not finished so we were expecting the onActivityResult to be triggered.

The function works well if the app is in foreground..

Using 0.9.7

Hope someone has some insight would be very much appreciated

Thank you

**Comment by akarimova** [comment]
fixed
