### ISSUE TITLE
Unable to instantiate receiver - Amazon

### ISSUE THREAD

**Issue by khangsile** [onepf/OpenIAB#383]
Hi, 

I'm trying to implement OpenIAB with the Google Play store and Amazon. The Google Play store works without any errors. However, when I've tried using the Amazon store, I get an error:

java.lang.RuntimeException: Unable to instantiate receiver com.amazon.device.iap.ResponseReceiver:
java.lang.ClassNotFoundException: Didn't find class "com.amazon.device.iap.ResponseReceiver" on path: DexPathList[[zip file"/data/app/com.example.app-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.example.app-1, /vendor/lib, /system/lib, /vendor/lib]]

I'm not sure why it cannot find the class. I have implemented the Amazon modifications per the tutorial by adding 

```
<!-- Amazon Store -->
    <receiver android:name="com.amazon.device.iap.ResponseReceiver" >
        <intent-filter>
            <action
                android:name="com.amazon.inapp.purchasing.NOTIFY"
                android:permission="com.amazon.inapp.purchasing.Permission.NOTIFY" />
        </intent-filter>
    </receiver>
```

to the Manifest. I have Open IAB installed as the latest .jar.

**Comment by orionnoir** [comment]
The sample is wrong in the page we copied from. That is NOT your mistake. thanks for pointing this out. We copied the receiver entry found in the AndroidManifest.xml in the samples for v2.0 and got it working. You wont get a callback until you do.
