### ISSUE TITLE
Not consuming items on build 0.9.7.2

### ISSUE THREAD

**Issue by hjupter** [onepf/OpenIAB#388]
Hi, I'm having issues with the unity plugin version 0.9.7.2 I can purchase just fine but items are not being consumed even if it says consme succeeded when I try to buy the item again it says item already owned, I noticed there was more commits after 0.9.7.2 tag on the git but I get other errors with that build. 

Please I need to fix this ASAP since its happening on my live game here: https://play.google.com/store/apps/details?id=com.NinjutsuGames.InfestedLand

**Comment by akarimova** [comment]
closed as outdated
