### ISSUE TITLE
Amazon crash when querying inventory and find previous purchase

### ISSUE THREAD

**Issue by appfamily** [onepf/OpenIAB#390]
I have a single IAP, to unlock the full game. I can buy it successfully.

If I uninstall and re-install the game, and return to my purchasing scene, it crashes during inventory query with the following backtrace (first amazon app tester throws an error, included):

11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): Error parsing offset: 
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): java.lang.NumberFormatException: Invalid long: ""
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at java.lang.Long.invalidLong(Long.java:124)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at java.lang.Long.parseLong(Long.java:345)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at java.lang.Long.parseLong(Long.java:318)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at com.amazon.sdktestclient.iap.command.PurchaseUpdatesCommandHandler.parseOffset(PurchaseUpdatesCommandHandler.java:122)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at com.amazon.sdktestclient.iap.command.PurchaseUpdatesCommandHandler.executeRequest(PurchaseUpdatesCommandHandler.java:49)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at com.amazon.sdktestclient.iap.command.IapCommandHandler.execute(IapCommandHandler.java:59)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at com.amazon.sdktestclient.command.CommandBroker.onHandleIntent(CommandBroker.java:30)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at android.os.Handler.dispatchMessage(Handler.java:102)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at android.os.Looper.loop(Looper.java:145)
11-16 21:35:18.662: W/AmazonAppTester/PurchaseUpdatesCommandHandler(16228): 	at android.os.HandlerThread.run(HandlerThread.java:61)
11-16 21:35:18.702: W/dalvikvm(20259): threadid=1: thread exiting with uncaught exception (group=0x41634d58)
11-16 21:35:18.702: E/AndroidRuntime(20259): FATAL EXCEPTION: main
11-16 21:35:18.702: E/AndroidRuntime(20259): Process: com.appfamily.PegPuzzle2Trial, PID: 20259
11-16 21:35:18.702: E/AndroidRuntime(20259): java.lang.NoSuchMethodError: com.amazon.device.iap.model.Product.getPrice
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at org.onepf.oms.appstore.AmazonAppstoreBillingService.a(SourceFile:299)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at org.onepf.oms.appstore.AmazonAppstoreBillingService.onProductDataResponse(SourceFile:282)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at com.amazon.device.iap.internal.a.c$1.run(SourceFile:216)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at android.os.Handler.handleCallback(Handler.java:755)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at android.os.Handler.dispatchMessage(Handler.java:95)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at android.os.Looper.loop(Looper.java:145)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at android.app.ActivityThread.main(ActivityThread.java:5262)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at java.lang.reflect.Method.invokeNative(Native Method)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at java.lang.reflect.Method.invoke(Method.java:515)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:826)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:642)
11-16 21:35:18.702: E/AndroidRuntime(20259): 	at dalvik.system.NativeStart.main(Native Method)

My setup:
- OpenIAB dev branch copy from 20141111
- Amazon's in-app-purchasing-2.0.1.jar
- Kindle Fire HDX 7

**Comment by reset** [comment]
@RomanZhilich @akarimova I'm experiencing this same problem within a Unity project while using:

* https://github.com/onepf/OpenIAB-Unity-Plugin/releases/tag/0.9.7.2
* Amazon's and in-app-purchase.jar version 2.0.1

It seems that the OpenIAB-Unity plugin was built using version 0.9.7.2 of the OpenIAB project which is the release before Amazon IAP 2.0 was supported. Are there any plans to update/release a new version of the OpenIAB-Unity plugin which will be compatible with the latest version of OpenIAB? Thank you!

**Comment by RomanZhilich** [comment]
Actually there are newer version. They're attached to OpenIAB releses: https://github.com/onepf/OpenIAB/releases

**Comment by reset** [comment]
@RomanZhilich thanks very much!
