### ISSUE TITLE
Yandex.Store fail to purchase item

### ISSUE THREAD

**Issue by int02h** [onepf/OpenIAB#391]
After calling launchPurchaseFlow() I received error: "IabResult: 4, Problem purchashing item. (response: 4:Item unavailable)". In Yandex.Store Developer Console all purchase items are added and configured. OpenIAB version is 0.9.7.2. Yandex Store app is installed on my device and yandex account is connected to store app.

**Comment by senscombo** [comment]
@int02h i alse encounter  that Yandex.Store asks me to provide credit card or phone information for tester account,but i cann't figure out what issue casuse this ,could you please tell me .
