### ISSUE TITLE
Permisson

### ISSUE THREAD

**Issue by JaimeCarbo** [onepf/OpenIAB#426]
Hi,

We have noticed that in our app your library shows up in the permissions as "com.tmoney.vending.INBILLING". Is this a bug?

**Comment by RomanZhilich** [comment]
I believe this permission is necessary for [T-Store](http://dev.tstore.co.kr/devpoc/index.omp) and it doesn't seem like a bug.

**Comment by akarimova** [comment]
Hi @JaimeCarbo,
to be honest, it is a bug.
The current library version doesn't support T-Store, we don't need to declare this permission here https://github.com/onepf/OpenIAB/blob/master/library/src/main/AndroidManifest.xml.
Will be removed in the nearest release.

**Comment by JaimeCarbo** [comment]
Hi @akarimova and @RomanZhilich 

Thank you for taking a look into this. I appreciate it.
