### ISSUE TITLE
Steps to integrate New Store with OpenIAB

### ISSUE THREAD

**Issue by aarteaga88** [onepf/OpenIAB#428]
What are the steps to integrate a new brand android store and make it compatible with the OpenIAB?, We already support In-App Billing.

Thanks

**Comment by akarimova** [comment]
Hi @aarteaga88,
could you please explain, do you already support our Open Billing, or is it your own?

**Comment by aarteaga88** [comment]
It is our own Billing, our company have 12 years of carrier billing experience on LatAm Market.

**Comment by akarimova** [comment]
I'm sorry for the delay in my reply
Please follow the same instructions that were suggested for https://github.com/onepf/OpenIAB/issues/382
