### ISSUE TITLE
If you press cancel button after successful purchase, IabHelper.OnIabPurchaseFinishedListener returns Failure

### ISSUE THREAD

**Issue by trimf** [onepf/OpenIAB#432]
If you press cancel button after successful purchase (on the screenshot), IabHelper.OnIabPurchaseFinishedListener returns Failure.
I'm using openiab-0.9.8.2 version.
![device-2015-01-14-181754](https://cloud.githubusercontent.com/assets/6950591/5740087/57121df4-9c11-11e4-85c0-3046e225c555.png)

However queryInventoryAsync returns purchase, and this is the only chance to process the purchase...

**Comment by akarimova** [comment]
Hi @trimf 
it is a known YS issue. They promised to fix it.

**Comment by akarimova** [comment]
We can't make a workaround.

**Comment by trimf** [comment]
Ок. Will be waiting for update.
