### ISSUE TITLE
problem: Item Already Owned

### ISSUE THREAD

**Issue by kiu123123123** [onepf/OpenIAB#438]
use purchaseProduct  first time is ok,   but second time display response 7: Item Already Owned

please help

**Comment by RomanZhilich** [comment]
Did you try calling ```consume()``` for purchased item?

**Comment by kiu123123123** [comment]
call OpenIAB.purchaseProduct(SKU)

**Comment by kiu123123123** [comment]
Unity OpenIAB don't have consume() function

**Comment by GrimReio** [comment]
Please take a look at this [example](https://github.com/onepf/OpenIAB-Unity-Plugin/blob/master/unity_plugin/unity_src/Assets/OpenIAB-demo/OpenIABTest.cs#L142)

**Comment by kiu123123123** [comment]
example _inventory is null,  can't run OpenIAB.consumeProduct(_inventory.GetPurchase(SKU));

**Comment by kiu123123123** [comment]
thanks ..   I fix it....
