### ISSUE TITLE
IllegalStateException in onFinishSetup because setup isn't done, with google play

### ISSUE THREAD

**Issue by Lakedaemon** [onepf/OpenIAB#442]
I'm handling InApp Billing in a fragment. 

In my  onIabSetupFinished callback, I'm calling helper.queryInventoryAsync only if 
the IabResult result is not null and has isSuccess()==true, yet, I'm getting this exception (I'm onlytesting on Google play for now, this might be a Google play inApp library issue) : 

java.lang.IllegalStateException: IAB helper setup is in progress. Can't perform operation: queryInventory

what am I doing wrong ? 
Basically, it looks like setup finished ok (because it passes result.isSuccess(), 
but the setupState variable wasn't set correctly (because checkSetupDone() throws an exception)
Here is the stackTrace : 

java.lang.IllegalStateException: IAB helper setup is in progress. Can't perform operation: queryInventory
at  org.onepf.oms.OpenIabHelper.checkSetupDone (OpenIabHelper.java : 1439)
at  org.onepf.oms.OpenIabHelper.queryInventoryAsync (OpenIabHelper.java : 1345)
at  org.onepf.oms.OpenIabHelper.queryInventoryAsync (OpenIabHelper.java : 1327)
at  org.onepf.oms.OpenIabHelper.queryInventoryAsync (OpenIabHelper.java : 1318)
at  org.onepf.oms.OpenIabHelper.queryInventoryAsync (OpenIabHelper.java : 1310)
at  org.lakedaemon.android.fragment.OpenBillingFragment.onIabSetupFinished (OpenBillingFragment.kt : 86)
at  org.onepf.oms.appstore.googleUtils.IabHelper$1.onServiceConnected (IabHelper.java : 267)
at  android.app.LoadedApk$ServiceDispatcher.doConnected (LoadedApk.java : 1106)
at  android.app.LoadedApk$ServiceDispatcher$RunConnection.run (LoadedApk.java : 1123)
at  android.os.Handler.handleCallback (Handler.java : 725)
at  android.os.Handler.dispatchMessage (Handler.java : 92)
at  android.os.Looper.loop (Looper.java : 137)
at  android.app.ActivityThread.main (ActivityThread.java : 5283)
at  java.lang.reflect.Method.invokeNativeNative Method
at  java.lang.reflect.Method.invoke (Method.java : 511)
at  com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java : 1102)
at  com.android.internal.os.ZygoteInit.main (ZygoteInit.java : 869)
at  dalvik.system.NativeStart.mainNative Method

And here is the relevant code in the fragment (in kotlin, it's a lot like java except it's easier to make null check)

    override fun onAttach(activity: Activity?) {
        super<Fragment>.onAttach(activity)
        helper = OpenIabHelper(activity, InAppBuyD.options)
        try {
            helper?.startSetup(this)
        } catch (e: Exception) {
            addError(e)
        } // binding the service
    }

 final override fun onIabSetupFinished(result: IabResult?): Unit = if (result?.isSuccess() ?:false) helper?.queryInventoryAsync(this) else {
        errors.add(result.toString())
        updateMenu()
    }

final override fun onActivityResult(requestCode: Int, resultCode: Int, data: Intent?): Unit = if (requestCode != REQUEST_CODE) super<Fragment>.onActivityResult(requestCode, resultCode, data) else {
        // Pass on the activity result to the helper for handling
        if (helper?.handleActivityResult(requestCode, resultCode, data) != true) {
            errors.add("InAppBuyActivity Returned with result : " + resultCode + data.toString())
            // not handled, so handle it ourselves (here's where you'd
            // perform any handling of activity results not related to in-app
            // billing...
            super<Fragment>.onActivityResult(requestCode, resultCode, data);
        } else L.info("onActivityResult handled by IABUtil.")

        updateMenu()
    }

**Comment by Lakedaemon** [comment]
Is it fixed with 0.9.8.3 ? 
I was linking against 0.9.8.2 (docs slightly behind the releases)

**Comment by RomanZhilich** [comment]
Hi.

It doesn't look like Google specific issue, but might be a synchronization issue with library.

My theory is: After successful setup you might be calling ```dispose()```  (most likely from onDetach()). This might be due to screen rotation, or some other configuration changes. Then you start setup allover, and only then you call ```quieryInventory()```.

Or you've encountered #429 issue, which should be fixed in [0.9.8.3](https://github.com/onepf/OpenIAB/releases/tag/0.9.8.3)

**Comment by Lakedaemon** [comment]
Thanks for the Reply. Hadn't thought of configuration changes

My fragment has setRetainInstance(true), so it should survive screen rotation and configuration changes (right ?) 

helper.dispose() is only called in onDestroy() which should happen when the activity is destroyed, 
then, the helper is set to null and queryInventory shouldn't be called if it is null (-> I might need to synchronize the helper)

Maybee I should dispose it in onDetach() ? 

But activity death is another matter (I think)



Also the call that produces the exception is called in onSetupFinished...after a isSuccess() check, 
so even after an activity recreation, the zombie helper should be setup  (right ?) 

I hope that this issue will be solved with 0.9.8.3 (it sounds plausible)
I compiled with 0.9.8.3.1 and will push it tonigth to my struggling users (hopefully, it'll make it disappear)


In my experience, the inAppBilling classes from Google are buggy / lack Checks and are unmaintained. I had to hack them a bit to make them work without throwing exception before I turned to openIAB. So, I'm not ruling out any bug from the Google side :) 
 
This sucks a bit to have to use an activity to make a license /inApp billing check :/

Also, doesn't the openIAB helper need a isDisposed() and hasAsyncTaskInProgress() methods ?

**Comment by RomanZhilich** [comment]
> My fragment has setRetainInstance(true), so it should survive screen rotation and configuration changes (right ?)

Yes, but the thing is - it will call ```onDetach()``` and ```onAttach()``` every time.
> helper.dispose() is only called in onDestroy() which should happen when the activity is destroyed, 
then, the helper is set to null and queryInventory shouldn't be called if it is null (-> I might need to synchronize the helper)

> Maybee I should dispose it in onDetach() ?

If you create helper in ```onAttach()``` you should dispose of it in ```onDetach()```, and if you dispose of it in ```onDestroy()``` it should be initialized in ```onCreate()``` and so on. 
> But activity death is another matter (I think)

I don't think it should. If you pass ```getActivity()``` as a context, link to it should only be kept during setup, and cleared afterwards.
> Also, doesn't the openIAB helper need a isDisposed() and hasAsyncTaskInProgress() methods?

It actually has ```getSetupState()``` method. As for ```hasAsyncTaskInProgress()```... I don't think it should be an issue.


To get rid of your issue, I hope following will be enough:
* Get your setup/dispose cycle right.
* Use  0.9.8.3 to get rid of synchronization issues.

Also I hope you don't keep link to initial Activity and use ```getActivity()``` wherever possible.

**Comment by akarimova** [comment]
@Lakedaemon was it helpful?

**Comment by Lakedaemon** [comment]
Yes, sorry not to have reported back sooner. 

I had messed my Fragment life cycle by setting the helper in Fragment.onCreate() and disposing of it in onDestroy().

Setting in onAttach and disposing in onDetach fixed my issue

**Comment by RomanZhilich** [comment]
Glad it worked out.
