### ISSUE TITLE
(Question) Why 2 unity packages for version 0.9.8.3?

### ISSUE THREAD

**Issue by ajaybirla** [onepf/OpenIAB#448]
Hello @akarimova,

Why there are 2 .unitypackage for version 0.9.8.3?

Why there is a different .unitypackage for Android Lollipop?

Which one should we use and why?

We don't want to make a separate build for Android Lollipop.

**Comment by RomanZhilich** [comment]
There's a bug with Amazon SDK. It doesn't use explicit intent to start service, and therefore crushes on Android Lollipop. I'm pretty sure Unity Lollipop package just doesn't support Amazon.

**Comment by ajaybirla** [comment]
Hello @RomanZhilich 

Thanks for replying but i can see "in-app-purchasing-2.0.1.jar" inside both unity packages, that is for Amazon? Right?

I want to support Amazon too. Which one should i use?

Does openiab-plugin-0.9.8.3.unitypackage supports Amazon?

**Comment by GrimReio** [comment]
I'm sorry, but Amazon library contains bug, that's why it doesn't work on lollipop right now.
Package for lollipop simply contains proper error handling.

**Comment by ajaybirla** [comment]
Thanks @GrimReio,

When you say Lollipop, you mean Lollipop on Amazon? Or Lollipop on Android?

If i use "openiab-plugin-0.9.8.3-lollipop.unitypackage" then it will work on all Android versions including Lollipop. Also it will work on all Amazon version excluding Lollipop? Right? Correct me if i'm wrong.

**Comment by RomanZhilich** [comment]
I'm not sure how you distinct regular Lollipop and Amazon lollipop.

The way I see it:
* If you use regular plugin on Lollipop, and try to purchase something with Amazon - it will crash.
* If you use Lollipop version of plugin and to the same - it will just report an error.

**Comment by ajaybirla** [comment]
Thanks @RomanZhilich, 

In this case, i'll suggest that you should remove regular plugin as it is causing unnecessary confusion. 

Also i am curious to know how can someone purchase with Amazon, if you are on Lollipop? Because Lollipop can only exist in a device with Google's Android OS installed in it and if you have Android then you can do in-app purchase only with Google not with Amazon.

Sorry to disturb you again.

**Comment by RomanZhilich** [comment]
> In this case, i'll suggest that you should remove regular plugin as it is causing unnecessary confusion.

That's probably what we're gonna do.

> if you have Android then you can do in-app purchase only with Google not with Amazon.

The whole point of this library is to provide alternative. You can install Amazon store on any android device and use it for billing. There's actually a quite a few stores we support https://github.com/onepf/OpenIAB/wiki#how-to-add-support-for

**Comment by ajaybirla** [comment]
Thanks @RomanZhilich for your kind support. Thanks again.
