### ISSUE TITLE
Subscriptions purchased from a Test account make queryInventoryAsync() fail

### ISSUE THREAD

**Issue by bilbo7833** [onepf/OpenIAB#464]
Google recently made purchasing in-app subscriptions from test accounts (set up in the Google Developer Console) possible, without charging real money for them. However, when using the `IabHelper.queryInventoryAsync()` method, these exact test subscriptions will be returned as having an empty `purchaseData` and `signature`. This will fail the `isValidDataSignature()` method in `IabHelper.java:925` and will return no inventory. Is there any way to get around this apparent bug from Google In-App-Billing and make the `queryInventoryAsync()` method return these incomplete Purchases?

**Comment by RomanZhilich** [comment]
Have you tried calling ```setVerifyMode(OpenIabHelper.Options.VERIFY_SKIP)``` on options builder?

**Comment by bilbo7833** [comment]
I just tried it and you're right, the `isValidDataSignature()` now returns `true`, but the `queryPurchases()` method fails with a `JSONException` two lines afterwards in the Purchase constructor:
`Purchase purchase = new Purchase(itemType, purchaseData, signature, appstore.getAppstoreName());`
Since the `purchaseData` is empty, no valid JSON can be extracted from it. I have two such subscriptions with empty data and they seem to be broken. Newer test subscriptions work fine and they don't show up in this list at all, so maybe it's actually a Google Play In-App Billing Issue and not an OpenIAB Issue after all :)
