### ISSUE TITLE
Sample app with openBilling implemented in a fragment

### ISSUE THREAD

**Issue by Lakedaemon** [onepf/OpenIAB#466]
Could we have a sample app with openBilling implemented in a fragment ? 

That's what I am doing in my app. I had to adapt the sample where openBilling is implemented in an activity and had to struggle with a few issues (where to call the openIAB methods (onAttach, onDetach), transmit the onActivityResult called by the lib in an activity to the fragment...).

It would be nice to have a reference imprementation for fragments.

**Comment by RomanZhilich** [comment]
Actually workflow should be pretty much the same, except for lifecycle calls (onAttach/onDetach as you mentioned). I gave a few comments on the matter in issue #442.
As for sample with fragment... To accomplish this, sample should either contain a lot of code duplication or majorly refactored. So unfortunately we likely won't do that.

**But** I promise to include Activity/Fragment samples out of the box for the upcoming version, written from scratch.
Early alpha should become public pretty soon (let's say days\weeks rather then months).

**Comment by Lakedaemon** [comment]
This would be nice thanks. :)

I'm surprised you had to rewrite this lib. It seems to be working quite nicely (only tested it with Google play and Amazon so far...doing it next on slideme, samsungApps).

**Comment by RomanZhilich** [comment]
Current version has some fundamental architectural flaws, mostly due to the fact it came from Google TrivialDrive sample. I'll try to explain the situation in the upcoming release notes.
