### ISSUE TITLE
 Authentication required for google

### ISSUE THREAD

**Issue by l33tconsultant** [onepf/OpenIAB#474]
Sorry to bother anyone with this -again-, but I have been trying unsuccessfully for a few days using Google and openiab.  I have 9.8.6 from maven.  My app is "published" (Green letters on top left of Google dev console).  uploaded my store items.  and followed directions several times, from scratch  on the wiki (copy & paste settings). I've checked and re-checked the key, and tried VERIFY_SKIP with same results.

the user is primary to the device, and is listed in Google console as a license tester.  I log into the app using said user and google+.  I've been working the problem for a few days, so I'm sure all of google settings are up to date. Version numbers match.  install the apk to device with -i switch.

OpenIabHelper.Options options = new OpenIabHelper.Options.Builder()
                .setVerifyMode(OpenIabHelper.Options.VERIFY_EVERYTHING)
                .addStoreKey(OpenIabHelper.NAME_GOOGLE, GOOGLE_KEY)
                .build();

I don't receive any available items from Google on the callback, and when I try to purchase, it give me the authentication required.

**Comment by RomanZhilich** [comment]
> listed in Google console as a license tester

Have you published your app in one of the testing channels (alpha/betta)? If yes, you must install the app via direct link provided in dev console. Link becomes available once your application becomes available from Google Play (it may take a few hours).
Usually ```authentication required``` means that either current user can't use this application (not listed as tester) or application is no signed with the correct keystore (same one you used with apk uploaded to Google).
Also please check your app version.

**Comment by l33tconsultant** [comment]
Thanks RomanZhillich,

Yes, I did publish to alpha. and then clicked publish, and I can download it from the play store with the special link.   I read that I can use the same versionNumber to test locally, but only if installing a signed apk with -i com.android.vending  I'm still not working. here is more code:

 OpenIabHelper.Options options = new OpenIabHelper.Options.Builder()
                .setVerifyMode(OpenIabHelper.Options.VERIFY_ONLY_KNOWN)
                .addStoreKey(OpenIabHelper.NAME_GOOGLE, GOOGLE_KEY)
                .setStoreSearchStrategy(OpenIabHelper.Options.SEARCH_STRATEGY_INSTALLER_THEN_BEST_FIT)
                .build();

        helper = new OpenIabHelper(context, options);
        helper.startSetup(new IabHelper.OnIabSetupFinishedListener() {
            public void onIabSetupFinished(IabResult result) {
                if (!result.isSuccess()) {
                    Log.d(TAG, "Problem setting up in-app billing: " + result);
                    return;
                }
                Log.d(TAG, "Setup successful. Querying inventory.");
                helper.queryInventoryAsync(true, arrayList, mGotInventoryListener);
            }
        });

this return a success in the listener, but no items, despite the fact that I have uploaded them and they are in active states.
When I push a SKU into buying, it errors with the authentication.

if I had a satoshi for every time I copied and pasted that public key, I'd  be a Bitcoin billionaire.

**Comment by RomanZhilich** [comment]
> but only if installing a signed apk with -i com.android.vending I'm still not working

So, when you download apk from Google Play it works, but when you install it manually - it doesn't?

**Comment by l33tconsultant** [comment]
I didn't say it works, are you saying it only works if it's downloaded from the play store?

**Comment by RomanZhilich** [comment]
> I didn't say it works

That's why I asked.
> are you saying it only works if it's downloaded from the play store

Actually it should work with what you're doing, but it definitely worth trying out version from Google Play.

**Comment by l33tconsultant** [comment]
Ouch - It will give you an authentication message error when your sku's are not lined up.  my sku's differed from the ArrayList I sent to what was on googleplay - by cApS
