### ISSUE TITLE
No Suitable Appstore Was Found (Amazon), Unity3D plugin

### ISSUE THREAD

**Issue by yuriythebest** [onepf/OpenIAB#476]
Hi! First of all thanks for your plugin! I'm trying to implement it for amazon. Getting this error:

The error is:

Problem setting up in-app billing: IabResult: 3, No suitable appstore was found (response: 3:Billing Unavailable)

my steps:

 did the stuff here:
https://github.com/onepf/OpenIAB/wiki/How-To-support-Amazon-Appstore

(except pro guard since I don't use that, also didn't map SKU's)

                if (Button("Initialize OpenIAB"))
		{
			var options = new Options();
			options.checkInventoryTimeoutMs = Options.INVENTORY_CHECK_TIMEOUT_MS * 2;
			options.discoveryTimeoutMs = Options.DISCOVER_TIMEOUT_MS * 2;
			options.checkInventory = false;
			options.verifyMode = OptionsVerifyMode.VERIFY_SKIP;
			
			options.availableStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON };
			options.prefferedStoreNames = new string[] { OpenIAB_Android.STORE_AMAZON }; 
			options.storeSearchStrategy = SearchStrategy.INSTALLER;
			
			// Transmit options and start the service
			OpenIAB.init(options);
		}

my device: Pipo M6 pro, android 4.2.2,
I'm using Unity3D 4.6.3 and OpenIAB 0.9.8.6

I downloaded the amazon tester environment, placed the JSON in my sd card's root, installed using adb, but am still getting the same error.
thanks in advance!

**Comment by akarimova** [comment]
similar to #482
