### ISSUE TITLE
How to know whether particular video Interstitial has been viewed completely before it was closed

### ISSUE THREAD

**Issue by OmerCeliker** [onepf/OpenIAB#483]
I am using openIAB for unity integration. Everything is working fine except this issue. What is the 
recommended approach after hooking in the callbacks to detect the issue above.
This may not be OpenIAB issue but I was not sure where to post this question. Thank you.

From my source code:

		interstitial = new MyInterstitialAd (adUnitId);
		// Register for ad events.
		interstitial.AdLoaded += HandleInterstitialLoaded;
		interstitial.AdFailedToLoad += HandleInterstitialFailedToLoad;
		interstitial.AdOpened += HandleInterstitialOpened;
		interstitial.AdClosing += HandleInterstitialClosing;
		interstitial.AdClosed += HandleInterstitialClosed;

	public void HandleInterstitialClosed (object sender, EventArgs args)
	{
		//user viewed the ad  and closed it  OR closed the ad before viewing ????
		Debug.Log ("HandleInterstitialClosed event received");

	}

**Comment by RomanZhilich** [comment]
Em, I'm pretty sure this has nothing to do with OpenIAB library.
It appears you're using some kind of ad framework and your question should probably be directed to it.
If this is vanilla Unity concept, them I'm afraid I'm not familiar with it and can't help. Sorry.
