### ISSUE TITLE
Authentication is required

### ISSUE THREAD

**Issue by Z6P0** [onepf/OpenIAB#486]
I updated my app on Google Play with latest OpenIAB version (0.9.8.6, native jar).
Since then, the customers cannot buy my in-app product.
The error is: "Authentication is required. You need to sign into your Google Account."

There is also this error in the logs:
BasicNetwork.performRequest: Unexpected response code 403 for https://android.clients.google.com/fdfe/preparePurchase

Any help is very welcome!

**Comment by akarimova** [comment]
Hello @Z6P0 
can't reproduce with our example

could you please share a link to your app?

Thank you,
AK

**Comment by Z6P0** [comment]
Hello,
The problem solved itself after 2-3 days, I don't know why. There was probably a glitch on the Play Store servers, I reported it to Google but never get any answer...

**Comment by akarimova** [comment]
Ok, thank you
