### ISSUE TITLE
Could not find method org.onepf... after upgrading from 0.9.8.1 to 0.9.8.2 (and so latest 0.9.8.6 too)

### ISSUE THREAD

**Issue by romanshuvalov** [onepf/OpenIAB#495]
I used 0.9.6, all was OK. After upgrading to latest 0.9.8.6 I got app crash on start with several `I/dalvikvm(11697): Could not find method org.onepf.oms.OpenIabHelper.handleActivityResult, referenced from...`-like lines in log.

I tested several versions of OpenIAB and found out that 0.9.8.1 is working, but 0.9.8.2 is not. When building with 0.9.8.2 there are also a lot of lines like 
```
       [dx] trouble processing:
       [dx] bad class file magic (cafebabe) or version (0033.0000)
       [dx] ...while parsing com/sec/android/iap/IAPServiceCallback$Stub.class
       [dx] ...while processing com/sec/android/iap/IAPServiceCallback$Stub.class
```
I don't understand **what exactly changed in 0.9.8.2** version that causes my app to fail even in building stage. 

I'm using compiled OpenIAB-x.x.x.x.jar from releases page and putting it to /libs folder.

MinSdkVersion is set to 10 for Android 2.3 support. Is it still supported by OpenIAB? (TargetSdkVersion is 18).

Java version:
```
java version "1.7.0_55"
OpenJDK Runtime Environment (IcedTea 2.4.7) (7u55-2.4.7-1ubuntu1~0.13.10.1)
OpenJDK 64-Bit Server VM (build 24.51-b03, mixed mode)
```
Thank you.

**Comment by RomanZhilich** [comment]
Hi.

I suspect this is the version when some Java 7 features (like diamond operator) were initially used.
Try adding following to you `build.gradle`:
```Groovy
compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
}
```

**Comment by romanshuvalov** [comment]
Thank you. But when I opened `build.gradle` I found this lines:
```
    ext {
        compileSdkVersion = 21
        buildToolsVersion = "21.1.2"
        minSdkVersion = 10
        targetSdkVersion = 21
    }
```

So I think I should update my SDK tools to 21 and set targetSdkVersion to 21, because it looks like OpenIAB can use SDK21 features (and minSdkVersion is still 10 which is nice). And if I will still get same errors even with version 21 of SDK, I'll try your solution. Thank you.

**Comment by romanshuvalov** [comment]
Yes, it worked (updated SDK to 22). 
Sorry for disturbing.
