### ISSUE TITLE
Canceling an in-app purchase of amazon app store results in error 6 instead of IABHELPER_USER_CANCELLED

### ISSUE THREAD

**Issue by Juweii** [onepf/OpenIAB#507]
Hello!
I think i have found an error in implementation of the amazon app store in app purchase.
In the OnIabPurchaseFinishedListener i have the following code:

            if (result.isFailure()) {
                if (result.getResponse() != IabHelper.IABHELPER_USER_CANCELLED) {
                    alert(String.format(getResources().getString(R.string.purchase_failed), result.getMessage()));
                }

                return;
            }

The alert shouldn't appear if the user just cancel the in-app purchase - but it shows error 6 (Error) instead of -1005 (IABHELPER_USER_CANCELLED).

Testes on android with openiab 0.9.8.7 + amazon in-app-purchasing 2.0.61.

Any chance to check for cancellation of the purchase?

With best regards,
Juergen

**Comment by RomanZhilich** [comment]
Amazon SDK just doesn't report reason for error, there's nothing to be done until they fix it.

**Comment by Juweii** [comment]
Oh ok, thank you.
Can you give me a fast if-code to check for the used market (if (market == AMAZON)) so i could change the output for amazon users to a more universal error message.

Thank you!
Juergen

**Comment by RomanZhilich** [comment]
Unfortunately there's no API for that. There are some historical reasons but it's not really relevant anymore.
Easiest way for you would be to use reflection to access [appstore](https://github.com/onepf/OpenIAB/blob/master/library/src/main/java/org/onepf/oms/OpenIabHelper.java#L219) variable.

As a more general solution I'd recommend checking out https://github.com/onepf/OPFIab . There you can use `BillingResponse#getProviderName()` to check billing provider.

**Comment by Juweii** [comment]
Ok, i will check this. Thank you!
