### ISSUE TITLE
Pressing back on Yandex purchase dialog returns IabHelper.BILLING_RESPONSE_RESULT_ERROR

### ISSUE THREAD

**Issue by markostamcar** [onepf/OpenIAB#52]
Thus I show the "Transaction could not be completed" dialog to the user. The correct response code for canceling should be IabHelper.IABHELPER_USER_CANCELLED like Google Play IabHelper does it.

**Comment by nkuznetsow** [comment]
I have same issue. When I press back device button in Yandex Store purchase dialog I receive next IabResult in onIabPurchaseFinished: "IabResult: 6, Problem purchasing item. (response: 6:Error)".

I have 2.41 version of Yandex Store.

Activity result intent extras has only RESPONSE_CODE key and it value is 6.

It seems to Yandex Store error. It must returns code 1, according to Google Play documentation.

I don't know how to contact with Yandex Store developers, but I know, that you have this ability. Please, provide them this information.
