### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by nanom1t** [onepf/OpenIAB#520]
**Nokia X2 Dual SIM**:

java.lang.NullPointerException
android.os.Parcel.readException(Parcel.java:1437)
android.os.Parcel.readException(Parcel.java:1385)
org.onepf.oms.IOpenAppstore$Stub$Proxy.isBillingAvailable(IOpenAppstore.java:231)
org.onepf.oms.appstore.OpenAppstore.isBillingAvailable(OpenAppstore.java:106)
org.onepf.oms.OpenIabHelper$11.run(OpenIabHelper.java:797)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
java.lang.Thread.run(Thread.java:841)

**Comment by nkuznetsow** [comment]
I have same issue on Nokia x2ds
